
logging:
  level:
    root: info

server:
  port: 8093

spring:
  application:
    name: project-example
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 500
        max-idle: 64
        min-idle: 2
        max-wait: 300





#
#elasticsearch:
#  ip: 127.0.0.1
#  port: 9200
#  user:
#  password:
#  connectTimeout: 1000
#  socketTimeout: 40000
#  connectionRequestTimeout: 1000
#  maxConnTotal: 100
#  maxConnPerRoute: 100
#  maxRetryTimeoutMillis: 300000